# -*- coding: utf-8 -*-
"""lb05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dAAOV9vphHVlBEfw7YsRfyjipYXY0Op5

01.	Pandas

a.	Import the pandas as pd

b.	Create the series

c.	Find the data type of the series

d.	Print the index of the element

e.	Multiply and add the element in the series

f.	Print the date

g.	Create the data frame

h.	Insert the given data frame and explain the output

i.	Find the datatype of data frame  

j.	Find the first few values of the data frame  

k.	Find the last records of the data frame

l.	Index values of data frame

m.	Find the column of the data frame

n.	Convert the data frame into numpy array

o.	Find the statistics summary of data frame

p.	Transpose the data frame

q.	Sort the data frame

r.	Retrieve the value from the data frame
"""

# 01. Pandas Complete Sheet

# a. Import the pandas as pd
import pandas as pd
import numpy as np

# b. Create the series
my_series = pd.Series([10, 20, 30, 40, 50])
print("Series:\n", my_series)

# c. Find the data type of the series
print("\nData type of Series:", type(my_series))

# d. Print the index of the element
print("\nIndex of Series:", my_series.index)

# e. Multiply and add the element in the series
print("\nSeries multiplied by 2:\n", my_series * 2)
print("Series added by 5:\n", my_series + 5)

# f. Print the date
print("\nToday's Date:", pd.Timestamp.today())

# g. Create the data frame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
print("\nDataFrame:\n", df)

# h. Insert the given data frame and explain the output
# (Output is already printed above; it shows rows and columns in tabular format)

# i. Find the datatype of data frame
print("\nData type of DataFrame:", type(df))

# j. Find the first few values of the data frame
print("\nFirst 2 records:\n", df.head(2))

# k. Find the last records of the data frame
print("\nLast 2 records:\n", df.tail(2))

# l. Index values of data frame
print("\nIndex values of DataFrame:", df.index)

# m. Find the column of the data frame
print("\nColumns of DataFrame:", df.columns)

# n. Convert the data frame into numpy array
print("\nDataFrame as NumPy array:\n", df.to_numpy())

# o. Find the statistics summary of data frame
print("\nStatistics summary:\n", df.describe(include='all'))

# p. Transpose the data frame
print("\nTransposed DataFrame:\n", df.T)

# q. Sort the data frame
print("\nDataFrame sorted by Age:\n", df.sort_values(by='Age'))

# r. Retrieve the value from the data frame
print("\nValue Retrieved (Age of Bob):", df.loc[1, 'Age'])

"""02.	Import the data set

a.	Filter the first five records of the data set heart.csv

b.	Find the data type of attributes

c.	Find the information of data set

d.	Find the summary statistics of the data set

e.	Retrieve the information cp greater than 2

"""

# Step 1: Import required libraries
import pandas as pd
from google.colab import files

# Step 2: Upload heart.csv file manually
print("Please upload the 'heart.csv' file:")
uploaded = files.upload()

# Step 3: Read the uploaded CSV file
df = pd.read_csv('heart.csv')

# Step 4a: Filter the first five records
print("\nFirst five records of the dataset:")
print(df.head())

# Step 4b: Find the data type of attributes
print("\nData types of attributes:")
print(df.dtypes)

# Step 4c: Find the information of the dataset
print("\nInformation about the dataset:")
print(df.info())

# Step 4d: Find the summary statistics of the dataset
print("\nSummary statistics of the dataset:")
print(df.describe())

# Step 4e: Retrieve the records where 'cp' > 2
print("\nRecords where 'cp' > 2:")
print(df[df['cp'] > 2])

"""03.	Data visualization  

a.	import the bank-data.csv file

b.	Retrieve the first five records in the data set

c.	Plot the data set

d.	Describe the data set

e.	Plot the data set income Vs children  

f.	Construct the bar chart for region

g.	Construct the scatter plot for income and children and set the title as income vs children

h.	Construct the histogram for children

"""

# Step a: Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# Step a: Upload the file
print("Please upload the 'bank-data.csv' file:")
uploaded = files.upload()

# Step a: Load the dataset
df = pd.read_csv('bank-data.csv')

# Step b: Retrieve the first five records
print("\nFirst five records:")
print(df.head())

# Step c: Plot the dataset (basic pairplot to visualize all numeric relationships)
print("\nPlotting pairplot of dataset (if numeric columns exist)...")
sns.pairplot(df.select_dtypes(include='number'))
plt.show()

# Step d: Describe the dataset
print("\nDescriptive statistics:")
print(df.describe())

# Step e: Plot income vs children
if 'income' in df.columns and 'children' in df.columns:
    plt.figure(figsize=(8, 5))
    sns.lineplot(data=df, x='income', y='children')
    plt.title("Income vs Children (Line Plot)")
    plt.xlabel("Income")
    plt.ylabel("Children")
    plt.grid(True)
    plt.show()
else:
    print("\nColumns 'income' or 'children' not found for line plot.")

# Step f: Construct the bar chart for 'region'
if 'region' in df.columns:
    plt.figure(figsize=(8, 5))
    df['region'].value_counts().plot(kind='bar', color='skyblue')
    plt.title("Bar Chart of Regions")
    plt.xlabel("Region")
    plt.ylabel("Count")
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.show()
else:
    print("\nColumn 'region' not found for bar chart.")

# Step g: Scatter plot for income and children with title
if 'income' in df.columns and 'children' in df.columns:
    plt.figure(figsize=(8, 5))
    sns.scatterplot(data=df, x='income', y='children')
    plt.title("Income vs Children (Scatter Plot)")
    plt.xlabel("Income")
    plt.ylabel("Children")
    plt.grid(True)
    plt.show()
else:
    print("\nColumns 'income' or 'children' not found for scatter plot.")

# Step h: Histogram for children
if 'children' in df.columns:
    plt.figure(figsize=(8, 5))
    df['children'].plot(kind='hist', bins=10, color='purple', edgecolor='black')
    plt.title("Histogram of Children")
    plt.xlabel("Children")
    plt.ylabel("Frequency")
    plt.grid(True)
    plt.show()
else:
    print("\nColumn 'children' not found for histogram.")

"""04.	Explanatory data analysis

a.	Import the libraries numpy, pandas, matplotlin.pyplot, seaborn

b.	Import the data set bank-data.csv as data

c.	Check the data type

d.	Check the data shape

e.	Check the attribute name of the data set

f.	Check the null values

g.	Remove the unwanted attribute

h.	Rename the Attribute name

i.	Construct the plot for pep

j.	Group the data sex and pep according to the count

k.	Construct the graph for pep vs sex

l.	Find the count of the attribute children according to the category

m.	Construct the graph for attribute children according to the category

n.	Construct the chart to illustrate pep, children and sex of the customer based on the count

"""

# Step a: Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files

# Step b: Upload the dataset
print("Please upload the 'bank-data.csv' file:")
uploaded = files.upload()

# Step b: Read the dataset as `data`
data = pd.read_csv('bank-data.csv')

# Step c: Check the data types
print("\nData types:")
print(data.dtypes)

# Step d: Check the shape of the data
print("\nShape of the dataset:")
print(data.shape)

# Step e: Check attribute names (columns)
print("\nAttribute (column) names:")
print(data.columns)

# Step f: Check for null values
print("\nNull values in each column:")
print(data.isnull().sum())

# Step g: Remove unwanted attribute (example: remove 'id' if exists)
if 'id' in data.columns:
    data.drop(columns=['id'], inplace=True)
    print("\nRemoved 'id' column.")
else:
    print("\nNo 'id' column to remove.")

# Step h: Rename attribute names (example renaming for clarity)
data.rename(columns={
    'pep': 'PEP',
    'sex': 'Sex',
    'children': 'Children',
    'income': 'Income'
}, inplace=True)

print("\nRenamed columns:")
print(data.columns)

# Step i: Construct the plot for PEP
if 'PEP' in data.columns:
    plt.figure(figsize=(6, 4))
    sns.countplot(x='PEP', data=data, palette='Set2')
    plt.title('Distribution of PEP')
    plt.show()
else:
    print("\nColumn 'PEP' not found for plot.")

# Step j: Group data by Sex and PEP and count
print("\nGrouped data by Sex and PEP:")
grouped_data = data.groupby(['Sex', 'PEP']).size().reset_index(name='Count')
print(grouped_data)

# Step k: Construct the graph for PEP vs Sex
plt.figure(figsize=(7, 5))
sns.countplot(x='Sex', hue='PEP', data=data, palette='pastel')
plt.title('PEP vs Sex')
plt.xlabel('Sex')
plt.ylabel('Count')
plt.legend(title='PEP')
plt.grid(True)
plt.show()

# Step l: Count of Children by category
print("\nCount of each category in 'Children':")
print(data['Children'].value_counts())

# Step m: Graph for Children by category
plt.figure(figsize=(6, 4))
sns.countplot(x='Children', data=data, palette='viridis')
plt.title('Distribution of Children')
plt.xlabel('Number of Children')
plt.ylabel('Count')
plt.grid(True)
plt.show()

# Step n: Chart for PEP, Children, and Sex
plt.figure(figsize=(10, 6))
sns.catplot(x='Children', hue='PEP', col='Sex', data=data, kind='count', height=5, aspect=1)
plt.subplots_adjust(top=0.8)
plt.suptitle('PEP, Children, and Sex Distribution')
plt.show()